version: '3'
services:
  api:
    container_name: Trab_angelo_docker
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - postgres
  postgres:
    container_name: Trab_db
    image: postgres:13-alpine
    
    networks:
      - docker-network
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: Trab_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  docker-network:
volumes:
  api_db_data: